# Generated by Django 3.1.5 on 2021-01-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0002_auto_20210125_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='seccion',
            field=models.CharField(max_length=20, verbose_name='Sección'),
        ),
    ]
